bot:
  name: "Hecate"
  debug: true
  token: "417140336:AAH4GQFJnkwiG-oqAELatk2yGxIKkWG_jQw"
  log: test.log
  aerospike:
    host: "192.168.64.1"
    port: 3000
    namespace: "content"
  resources:
    images: /data/images
    help: resources/help.msg
    games: resources/games.json
    messages: resources/messages.json
    database: resources/users.db
