bot:
  name: "Hecate"
  debug: true
  token: "none"
  log: test.log
  aerospike:
    host: "192.168.64.1"
    port: 3000
    namespace: "content"
  resources:
    images: /data/images
  commands:
    help: resources/help.msg
    games: resources/games.json
